//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadNfe.NfeDownloadNF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeDownloadNF", ConfigurationName="NfeDownloadNF.NfeDownloadNFSoap")]
    public interface NfeDownloadNFSoap {
        
        // CODEGEN: Generating message contract since the operation nfeDownloadNF is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NfeDownloadNF/nfeDownloadNF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DownloadNfe.NfeDownloadNF.nfeDownloadNFResponse nfeDownloadNF(DownloadNfe.NfeDownloadNF.nfeDownloadNFRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeDownloadNF")]
    public partial class nfeCabecMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versaoDadosField;
        
        private string cUFField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string versaoDados {
            get {
                return this.versaoDadosField;
            }
            set {
                this.versaoDadosField = value;
                this.RaisePropertyChanged("versaoDados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string cUF {
            get {
                return this.cUFField;
            }
            set {
                this.cUFField = value;
                this.RaisePropertyChanged("cUF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeDownloadNFRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeDownloadNF")]
        public DownloadNfe.NfeDownloadNF.nfeCabecMsg nfeCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeDownloadNF", Order=0)]
        public System.Xml.XmlNode nfeDadosMsg;
        
        public nfeDownloadNFRequest() {
        }
        
        public nfeDownloadNFRequest(DownloadNfe.NfeDownloadNF.nfeCabecMsg nfeCabecMsg, System.Xml.XmlNode nfeDadosMsg) {
            this.nfeCabecMsg = nfeCabecMsg;
            this.nfeDadosMsg = nfeDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeDownloadNFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NfeDownloadNF", Order=0)]
        public System.Xml.XmlNode nfeDownloadNFResult;
        
        public nfeDownloadNFResponse() {
        }
        
        public nfeDownloadNFResponse(System.Xml.XmlNode nfeDownloadNFResult) {
            this.nfeDownloadNFResult = nfeDownloadNFResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NfeDownloadNFSoapChannel : DownloadNfe.NfeDownloadNF.NfeDownloadNFSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NfeDownloadNFSoapClient : System.ServiceModel.ClientBase<DownloadNfe.NfeDownloadNF.NfeDownloadNFSoap>, DownloadNfe.NfeDownloadNF.NfeDownloadNFSoap {
        
        public NfeDownloadNFSoapClient() {
        }
        
        public NfeDownloadNFSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NfeDownloadNFSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NfeDownloadNFSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NfeDownloadNFSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DownloadNfe.NfeDownloadNF.nfeDownloadNFResponse DownloadNfe.NfeDownloadNF.NfeDownloadNFSoap.nfeDownloadNF(DownloadNfe.NfeDownloadNF.nfeDownloadNFRequest request) {
            return base.Channel.nfeDownloadNF(request);
        }
        
        public System.Xml.XmlNode nfeDownloadNF(DownloadNfe.NfeDownloadNF.nfeCabecMsg nfeCabecMsg, System.Xml.XmlNode nfeDadosMsg) {
            DownloadNfe.NfeDownloadNF.nfeDownloadNFRequest inValue = new DownloadNfe.NfeDownloadNF.nfeDownloadNFRequest();
            inValue.nfeCabecMsg = nfeCabecMsg;
            inValue.nfeDadosMsg = nfeDadosMsg;
            DownloadNfe.NfeDownloadNF.nfeDownloadNFResponse retVal = ((DownloadNfe.NfeDownloadNF.NfeDownloadNFSoap)(this)).nfeDownloadNF(inValue);
            return retVal.nfeDownloadNFResult;
        }
    }
}
